# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TimeLeft < Formula
  desc ""
  homepage "https://github.com/ismtabo/time-left"
  version "1.1.0-SNAPSHOT-fe332f3"

  depends_on "gtk+3" if OS.linux?
  depends_on "libayatana-appindicator" if OS.linux?
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/ismtabo/time-left/releases/download/v1.1.0/time-left_1.1.0-SNAPSHOT-fe332f3_linux_amd64.tar.gz"
    sha256 "71bbb7c7a5f80be588e9e9859ebe516f8a4420782322af65c6a1df94d9c6ce63"
    def install
      bin.install "time-left"
    end
  end

  head "https://github.com/ismtabo/time-left.git", branch: "main"

  def post_install
    pkgetc.install "config.yaml"
  end

  service do
    run: [opt_bin, "--config", pkgetc/"config.yaml"]
  end
end
